spring.application.name=quiz-app

server.port=8080

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/quiz_app
spring.datasource.username=postgres
spring.datasource.password=student1
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Show SQL values (VERY helpful for learning)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# CONNECTION POOL (HikariCP)
# ===============================
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.connection-timeout=30000

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ===============================
# SPRING SECURITY (DEBUGGING)
# ===============================
#logging.level.org.springframework.security=DEBUG

# ===============================
# JACKSON (JSON)
# ===============================
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null

# ===============================
# SERVER ERROR (DEV FRIENDLY)
# ===============================
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

# ===============================
# TIMEZONE
# ===============================
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# OAUTH2 (Google & GitHub)
# ===============================
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=email,profile

